version: "3.8"

services:
  saleserp-app:
    build: ./sales
    container_name: saleserp-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/saleserp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    restart: always

  mysql:
    image: mysql:8.0
    container_name: saleserp-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: saleserp
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
